// Code generated by ogen, DO NOT EDIT.

package openshock

import (
	"github.com/google/uuid"
)

// AccountPasswordResetCheckValidParams is parameters of Account_PasswordResetCheckValid operation.
type AccountPasswordResetCheckValidParams struct {
	// The id of the password reset.
	PasswordResetId uuid.UUID
	// The secret of the password reset.
	Secret string
}

// AccountPasswordResetCompleteParams is parameters of Account_PasswordResetComplete operation.
type AccountPasswordResetCompleteParams struct {
	// The id of the password reset.
	PasswordResetId uuid.UUID
	// The secret of the password reset.
	Secret string
}

// DevicePairParams is parameters of Device_Pair operation.
type DevicePairParams struct {
	// The pair code to pair with.
	PairCode string
}

// DevicePairDEPRECATEDParams is parameters of Device_Pair_DEPRECATED operation.
type DevicePairDEPRECATEDParams struct {
	// The pair code to pair with.
	PairCode string
}

// DevicesEditDeviceParams is parameters of Devices_EditDevice operation.
type DevicesEditDeviceParams struct {
	DeviceId uuid.UUID
}

// DevicesGetDeviceByIdParams is parameters of Devices_GetDeviceById operation.
type DevicesGetDeviceByIdParams struct {
	DeviceId uuid.UUID
}

// DevicesGetLiveControlGatewayInfoParams is parameters of Devices_GetLiveControlGatewayInfo operation.
type DevicesGetLiveControlGatewayInfoParams struct {
	DeviceId uuid.UUID
}

// DevicesGetOtaUpdateHistoryParams is parameters of Devices_GetOtaUpdateHistory operation.
type DevicesGetOtaUpdateHistoryParams struct {
	// Id of the device.
	DeviceId uuid.UUID
}

// DevicesGetPairCodeParams is parameters of Devices_GetPairCode operation.
type DevicesGetPairCodeParams struct {
	DeviceId uuid.UUID
}

// DevicesGetShockersParams is parameters of Devices_GetShockers operation.
type DevicesGetShockersParams struct {
	// The device id.
	DeviceId uuid.UUID
}

// DevicesRegenerateDeviceTokenParams is parameters of Devices_RegenerateDeviceToken operation.
type DevicesRegenerateDeviceTokenParams struct {
	// The id of the device to regenerate the token for.
	DeviceId uuid.UUID
}

// DevicesRemoveDeviceParams is parameters of Devices_RemoveDevice operation.
type DevicesRemoveDeviceParams struct {
	// The id of the device to delete.
	DeviceId uuid.UUID
}

// PublicGetShareLinkParams is parameters of Public_GetShareLink operation.
type PublicGetShareLinkParams struct {
	ShareLinkId uuid.UUID
}

// ShareLinksAddShockerParams is parameters of ShareLinks_AddShocker operation.
type ShareLinksAddShockerParams struct {
	ShareLinkId uuid.UUID
	ShockerId   uuid.UUID
}

// ShareLinksDeleteShareLinkParams is parameters of ShareLinks_DeleteShareLink operation.
type ShareLinksDeleteShareLinkParams struct {
	ShareLinkId uuid.UUID
}

// ShareLinksEditShockerParams is parameters of ShareLinks_EditShocker operation.
type ShareLinksEditShockerParams struct {
	ShareLinkId uuid.UUID
	ShockerId   uuid.UUID
}

// ShareLinksPauseShockerParams is parameters of ShareLinks_PauseShocker operation.
type ShareLinksPauseShockerParams struct {
	ShareLinkId uuid.UUID
	ShockerId   uuid.UUID
}

// ShareLinksRemoveShockerParams is parameters of ShareLinks_RemoveShocker operation.
type ShareLinksRemoveShockerParams struct {
	ShareLinkId uuid.UUID
	ShockerId   uuid.UUID
}

// SharesDeleteShareCodeParams is parameters of Shares_DeleteShareCode operation.
type SharesDeleteShareCodeParams struct {
	ShareCodeId uuid.UUID
}

// SharesLinkShareCodeParams is parameters of Shares_LinkShareCode operation.
type SharesLinkShareCodeParams struct {
	ShareCodeId uuid.UUID
}

// ShockerEditShockerParams is parameters of Shocker_EditShocker operation.
type ShockerEditShockerParams struct {
	ShockerId uuid.UUID
}

// ShockerGetShockerByIdParams is parameters of Shocker_GetShockerById operation.
type ShockerGetShockerByIdParams struct {
	ShockerId uuid.UUID
}

// ShockerGetShockerLogsParams is parameters of Shocker_GetShockerLogs operation.
type ShockerGetShockerLogsParams struct {
	ShockerId uuid.UUID
	Offset    OptInt32
	Limit     OptInt32
}

// ShockerGetShockerSharesParams is parameters of Shocker_GetShockerShares operation.
type ShockerGetShockerSharesParams struct {
	// Id of the shocker.
	ShockerId uuid.UUID
}

// ShockerPauseShockerParams is parameters of Shocker_PauseShocker operation.
type ShockerPauseShockerParams struct {
	ShockerId uuid.UUID
}

// ShockerRemoveShockerParams is parameters of Shocker_RemoveShocker operation.
type ShockerRemoveShockerParams struct {
	ShockerId uuid.UUID
}

// ShockerShockerShareCodeCreateParams is parameters of Shocker_ShockerShareCodeCreate operation.
type ShockerShockerShareCodeCreateParams struct {
	ShockerId uuid.UUID
}

// ShockerShockerShareCodeListParams is parameters of Shocker_ShockerShareCodeList operation.
type ShockerShockerShareCodeListParams struct {
	ShockerId uuid.UUID
}

// ShockerShockerShareCodePauseParams is parameters of Shocker_ShockerShareCodePause operation.
type ShockerShockerShareCodePauseParams struct {
	ShockerId        uuid.UUID
	SharedWithUserId uuid.UUID
}

// ShockerShockerShareCodeRemoveParams is parameters of Shocker_ShockerShareCodeRemove operation.
type ShockerShockerShareCodeRemoveParams struct {
	ShockerId        uuid.UUID
	SharedWithUserId uuid.UUID
}

// ShockerShockerShareCodeUpdateParams is parameters of Shocker_ShockerShareCodeUpdate operation.
type ShockerShockerShareCodeUpdateParams struct {
	ShockerId        uuid.UUID
	SharedWithUserId uuid.UUID
}

// TokensDeleteTokenParams is parameters of Tokens_DeleteToken operation.
type TokensDeleteTokenParams struct {
	TokenId uuid.UUID
}

// TokensEditTokenParams is parameters of Tokens_EditToken operation.
type TokensEditTokenParams struct {
	TokenId uuid.UUID
}

// TokensGetTokenByIdParams is parameters of Tokens_GetTokenById operation.
type TokensGetTokenByIdParams struct {
	TokenId uuid.UUID
}
