// Code generated by ogen, DO NOT EDIT.
package openshock

type AccountLoginRes interface {
	accountLoginRes()
}

type AccountLoginV2Res interface {
	accountLoginV2Res()
}

type AccountPasswordResetCheckValidRes interface {
	accountPasswordResetCheckValidRes()
}

type AccountPasswordResetCompleteRes interface {
	accountPasswordResetCompleteRes()
}

type AccountSignUpRes interface {
	accountSignUpRes()
}

type AccountSignUpV2Res interface {
	accountSignUpV2Res()
}

type AdminGetOnlineDevicesRes interface {
	adminGetOnlineDevicesRes()
}

type DeviceGetLiveControlGatewayRes interface {
	deviceGetLiveControlGatewayRes()
}

type DevicePairDEPRECATEDRes interface {
	devicePairDEPRECATEDRes()
}

type DevicePairRes interface {
	devicePairRes()
}

type DevicesEditDeviceRes interface {
	devicesEditDeviceRes()
}

type DevicesGetDeviceByIdRes interface {
	devicesGetDeviceByIdRes()
}

type DevicesGetLiveControlGatewayInfoRes interface {
	devicesGetLiveControlGatewayInfoRes()
}

type DevicesGetOtaUpdateHistoryRes interface {
	devicesGetOtaUpdateHistoryRes()
}

type DevicesGetPairCodeRes interface {
	devicesGetPairCodeRes()
}

type DevicesGetShockersRes interface {
	devicesGetShockersRes()
}

type DevicesRegenerateDeviceTokenRes interface {
	devicesRegenerateDeviceTokenRes()
}

type DevicesRemoveDeviceRes interface {
	devicesRemoveDeviceRes()
}

type PublicGetShareLinkRes interface {
	publicGetShareLinkRes()
}

type ShareLinksAddShockerRes interface {
	shareLinksAddShockerRes()
}

type ShareLinksDeleteShareLinkRes interface {
	shareLinksDeleteShareLinkRes()
}

type ShareLinksEditShockerRes interface {
	shareLinksEditShockerRes()
}

type ShareLinksPauseShockerRes interface {
	shareLinksPauseShockerRes()
}

type ShareLinksRemoveShockerRes interface {
	shareLinksRemoveShockerRes()
}

type SharesDeleteShareCodeRes interface {
	sharesDeleteShareCodeRes()
}

type SharesLinkShareCodeRes interface {
	sharesLinkShareCodeRes()
}

type ShockerEditShockerRes interface {
	shockerEditShockerRes()
}

type ShockerGetShockerByIdRes interface {
	shockerGetShockerByIdRes()
}

type ShockerGetShockerLogsRes interface {
	shockerGetShockerLogsRes()
}

type ShockerGetShockerSharesRes interface {
	shockerGetShockerSharesRes()
}

type ShockerPauseShockerRes interface {
	shockerPauseShockerRes()
}

type ShockerRegisterShockerRes interface {
	shockerRegisterShockerRes()
}

type ShockerRemoveShockerRes interface {
	shockerRemoveShockerRes()
}

type ShockerSendControlDEPRECATEDRes interface {
	shockerSendControlDEPRECATEDRes()
}

type ShockerSendControlRes interface {
	shockerSendControlRes()
}

type ShockerShockerShareCodeCreateRes interface {
	shockerShockerShareCodeCreateRes()
}

type ShockerShockerShareCodeListRes interface {
	shockerShockerShareCodeListRes()
}

type ShockerShockerShareCodePauseRes interface {
	shockerShockerShareCodePauseRes()
}

type ShockerShockerShareCodeRemoveRes interface {
	shockerShockerShareCodeRemoveRes()
}

type ShockerShockerShareCodeUpdateRes interface {
	shockerShockerShareCodeUpdateRes()
}

type TokensDeleteTokenRes interface {
	tokensDeleteTokenRes()
}

type TokensEditTokenRes interface {
	tokensEditTokenRes()
}

type TokensGetTokenByIdRes interface {
	tokensGetTokenByIdRes()
}
